### PR TITLE
Split additional tools

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to the discussion here: https://github.com/jhipster/jhipster-devbox/issues/82
It's in Work In Progress, as I can't test my code right now..

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
it seems to be OK, excepting the clone jhipster-devbox, as there is no `tools` folder, because this PR is not accepted yet

**Comment by cbornet** [comment]
As for the mongo client, note that there's one included into the mongo docker container.
You can start it with `docker exec -it docker_myapp-mongodb_1 mongo`
Advantage : it has the same version as the mongod server which is not the case of the ubuntu mongo-clients. Using the ubuntu one is even not very good because you can't see the collection indexes.
So I wonder if we shouldn't just remove mongo install and document how to use the one in docker instead.

**Comment by cbornet** [comment]
Now you may want a mongo client to access a staging/prod DB so maybe we can keep the mongo cli installer. But we should install from site download to get the latest version.

**Comment by pascalgrimaud** [comment]
yes, all the scripts can be improved

**Pull request merged**
