### PR TITLE
Install VS Code and uninstall Atom

### LINKED ISSUE #60: Install VSCode
Since everybody likes VSCode, we should install it instead of Atom (very easy vith ubuntu-make)
What extensions would you like to see installed ?

### PR DESCRIPTION
**Pull request by cbornet**
Fix #60

### CODE REVIEW

**Comment by jdubois** [comment]
Looks like this broke the build:

==> default: Downloading and installing requirements
==> default: Installing Visual Studio Code
==> default: ln:
==> default: failed to create symbolic link '.local/share/umake/bin/visual-studio-code'
==> default: : No such file or directory
==> default: sed: can't read .local/share/applications/visual-studio-code.desktop: No such file or directory
==> default: sed: can't read .local/share/umake/ide/visual-studio-code/bin/code: No such file or directory
==> default: /tmp/vagrant-shell: 143: /tmp/vagrant-shell:
==> default: visual-studio-code: not found
==> default: /tmp/vagrant-shell: 144: /tmp/vagrant-shell:
==> default: visual-studio-code: not found
==> default: /tmp/vagrant-shell: 145: /tmp/vagrant-shell:
==> default: visual-studio-code: not found
==> default: /tmp/vagrant-shell: 146: /tmp/vagrant-shell:
==> default: visual-studio-code: not found
==> default: /tmp/vagrant-shell: 147: /tmp/vagrant-shell:
==> default: visual-studio-code: not found
==> default: /tmp/vagrant-shell: 148: /tmp/vagrant-shell:
==> default: visual-studio-code: not found

**Comment by cbornet** [comment]
I look at it right now

**Comment by jdubois** [comment]
Don't worry, I'm doing the release anyway -> people can still install it with umake

**Comment by cbornet** [comment]
I forgot a to add a ```cd ~``` to get to the home directory before creating the link

**Comment by cbornet** [comment]
Or better to use absolute paths.

**Pull request merged**
