### PR TITLE
install Kitematic from official github deb package

### LINKED ISSUE #53: Add Kitematic
It would be useful to have Kitematic in the devbox as it can now be packaged as a .deb (see [this kitematic PR](https://github.com/docker/kitematic/pull/1677)).

The only problem is that we have to build the .deb ourself, I don't see it being distributed by Docker any time soon as the Linux support is community contributed.

To try it:
```
curl -O https://github.com/PierreBesson/jhipster-devbox/blob/install-kitematic/packages/Kitematic_0.10.2-1_amd64.deb
sudo dpkg -i dist/Kitematic_0.10.2-1_amd64.deb
```

### PR DESCRIPTION
**Pull request by PierreBesson**
fix #53

### CODE REVIEW

**Comment by jdubois** [comment]
I tried to upgrade to the latest 0.12.0 version, and it doesn't work.... I've heard Kitematic would be deprecated, so maybe we should revert this change?

**Comment by PierreBesson** [comment]
@jdubois I didn't know it was getting deprecated. Then what will replace it ?

It's not essential to have Kitematic anyway. It takes a lot of space. Probably more than 100 MB as it embeds electron. I just thought that it might be nice to have for people who are getting started with Docker.

**Comment by jdubois** [comment]
Well, that's what I heard from people working at Docker, but I don't know if that's true.
Anyway, if that's taking 100 MB, we should remove it, it's just too much space.

**Comment by jdubois** [comment]
Done at https://github.com/jhipster/jhipster-devbox/commit/7a2f7de87165ee0ef91cc3052c46ea4fd20a2b29

**Comment by FrenchBen** [comment]
The deb file should only be about 33MB zipped
I work on Kitematic and there hasn't been any talk of deprecating it. However there are some talks as to what it needs to become, especially with the native features that Docker for Mac/Windows bring to the table. 

It's still maintained and will still have releases on a regular schedule.

**Pull request merged**
