### PR TITLE
Install pgadmin and datastax devcenter

### PR DESCRIPTION
**Pull request by cbornet**
I also cleaned the STS archive
@jdubois, should we have GUI tools also for mongo and ElasticSearch ?

### CODE REVIEW

**Comment by cbornet** [comment]
I also installed datastax opscenter in my personnal vagrant, maybe this could also be added.

**Comment by cbornet** [comment]
Arf ! The docker-hub cassandra image doesn't have the datastax-agent nor ssh so it's unusable with opscenter at the moment. To make it work we would need to put the datastax-agent in our own cassandra dockerfile.

**Comment by jdubois** [comment]
Can you make separate PRs for all this?
Anyway don't worry too much about Cassandra, let's hold this for later: only 0,5% of our users use Cassandra, so this is definitely not a priority (even if I'm a big Cassandra fan!)

**Comment by pascalgrimaud** [comment]
In generator-jhipster, we already use our own cassandra Dockerfile to inject CQL files :
https://github.com/jhipster/generator-jhipster/blob/master/app/templates/_Dockerfile_cassandra

@cbornet : you can add what it needed here

**Comment by cbornet** [comment]
OK, I'll cut this in two.
@pascalgrimaud Yes, that's what I'm looking at. There are other difficulties : the IP adress of the opscenter must be known by the agent. So the best way is probably to have a dockerized opscenter so that everything can be linked together with docker-compose.

**Pull request closed without merging**
