### PR TITLE
Install yarn and use it to install global packages

### LINKED ISSUE #68: Install yarn
obviously

### PR DESCRIPTION
**Pull request by cbornet**
Fix #68

### CODE REVIEW

**Comment by cbornet** [comment]
To link a git cloned generator-jhipster:
* In the cloned folder: `yarn link`
* In the project folder: `yarn link generator-jhipster`

**Comment by pascalgrimaud** [comment]
@cbornet : you need to rebase ;)

**Comment by cbornet** [comment]
Yes. I'll do it for JHipster 4.

**Comment by jdubois** [comment]
Can you check the conflict? I should do a release soon, I'll have a look

**Comment by cbornet** [comment]
The conflict is on the jhipster version. Will you merge before changing it again ?

**Comment by jdubois** [comment]
OK, don't worry I'll do it

**Pull request merged**
