### PR TITLE
customized vm to share clipboard and enable drag'n drop

### PR DESCRIPTION
**Pull request by pasali**

### CODE REVIEW

**Comment by jdubois** [comment]
I'm always doing this manually, so +1 for me
But I don't understand why this isn't the default with VirtualBox -> is there some issue on some platform??

**Comment by pasali** [comment]
I think it's disabled because it is security-related thing. Default VirtualBox settings doesn't allow you to access host OS resources like files, folder, NAT, clipboard etc.

**Comment by cbornet** [comment]
There is a small alignment issue. Can you indent with 8 spaces and not a TAB ?

**Comment by cbornet** [comment]
I also like to have the file drag'n drop enabled.

**Comment by pasali** [comment]
fixed indentation problem.

**Comment by pasali** [comment]
i 've just added drag'n drop feature to my PR

**Pull request merged**
