### PR TITLE
Fixes devbox image building issue

### PR DESCRIPTION
**Pull request by BhawaniSingh**
- Changed base image from "bento/ubuntu-18.04" to "ubuntu/bionic64"
- Jdk 11 is installed by default instead of JDK 8
- Updated generator-jhipster to v6.0.0

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks a lot @BhawaniSingh !
Hope it will fix the DevBox

**Comment by pascalgrimaud** [comment]
Just tested and it works fine !
Thanks so much @BhawaniSingh : I'm merging this

**Comment by jdubois** [comment]
Awesome work @BhawaniSingh you totally deserve to be the official maintainer of the project! I'll organize this during the week.

**Comment by BhawaniSingh** [comment]
@jdubois Thanks

**Pull request merged**
