### PR TITLE
Add pgadmin

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Comment by jdubois** [comment]
OK, but as Postgresql is not installed, is it really a good thing?

**Comment by cbornet** [comment]
I still think we should have docker installed ! So that after a project generation, do a docker-compose to have the DB you selected for this project up and running.

**Comment by cbornet** [comment]
We could also dockerize phpmyadmin as it is a web interface. So that you have phpmyadmin spawned together with postgresql

**Comment by cbornet** [comment]
Maybe we could have prepared installation scripts that are commented in the Vagrantfile for optional softwares. What do you think ?

**Comment by jdubois** [comment]
As I just closed #10 I know I'm not being 100% logical with merging this. We should have something for Cassandra and MongoDB too... But it's a small package and a lot of people use Postgresql.

**Pull request merged**
