### PR TITLE
Install FiraCode font and use it in VS Code

### PR DESCRIPTION
**Pull request by cbornet**
Best font ever ! See https://github.com/tonsky/FiraCode

### CODE REVIEW

**Comment by cbornet** [comment]
Fixed issue with path

**Comment by cbornet** [comment]
Resolved conflict

**Comment by jdubois** [comment]
The more stuff we install, the more risks we have the build fail... I'm not a big fan of this one, it's just a font, nothing very important

**Comment by cbornet** [comment]
What makes Firacode a better font than the others is its use of ligatures so it really enhances the code lisibility.

**Comment by jdubois** [comment]
Sorry @cbornet but this image is already a huge pain to build, I would like to stop adding more stuff to download

**Pull request closed without merging**
