### PR TITLE
Use ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by jdubois** [comment]
There are several issues with this release:

- The current "bento" image was built with a development version of Ubuntu 18.04 (version v201803.24.0), so it's not the final stable built
- Our installation script doesn't work with it, there are several parts that do not work anymore

-> let's wait until there is a stable release of Ubuntu 18.04 on Vagrant

**Comment by pascalgrimaud** [comment]
yes, let's wait !

**Comment by robertmilowski** [comment]
Hi
 seems that issue is with update for keyboard-configuration.

I solve it temporary by adding hold mark for this update in script.sh

apt-mark hold keyboard-configuration
apt-get update
apt-get -y upgrade
apt-mark unhold keyboard-configuration

**Comment by pascalgrimaud** [comment]
Thanks @robertmilowski : would you like to contribute, so it will get the credits for your suggestion ? If yes, I can close this PR and you'll open a new one.

A new version of bento/ubuntu-18.04 has been 20 days ago, so we should give a try:
https://app.vagrantup.com/bento/boxes/ubuntu-18.04

**Comment by pascalgrimaud** [comment]
See https://github.com/jhipster/jhipster-devbox/pull/94

**Pull request closed without merging**
