### PR TITLE
Install docker, docker-compose and provide .m2

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Test the provision only 1 time (my connexion isn't good enough). Then :
* generate app
* start mongodb container
* start app

@cbornet : maybe can you try it if you have time ?

### CODE REVIEW

**Comment by cbornet** [comment]
OK. I'll try it asap.
@jdubois should we also remove MySQL from vagrant ? After a jhipster project is generated, a simple ```docker-compose up -d``` and you have the database you chose up and running :clap:

**Comment by jdubois** [comment]
In that case, yes, it should be removed!
That's really badass to use docker compose inside Vagrant!

**Comment by jdubois** [comment]
I'm not merging this yet, as I'd like to have a first release soon and Docker adds quite a bit of new things to tests and validate

**Comment by cbornet** [comment]
Tested OK (and awesome) on my side !

Now I want to have a cassandra multi-node cluster when I compose prod profile ! Then I will be uber-hipster :smile: !

**Comment by cbornet** [comment]
And it's ```sudo docker-compose up -d```, not ```docker-compose up -d``` as I wrote earlier.

**Comment by cbornet** [comment]
@pascalgrimaud Can you fix the merge conflict and probably add a link in README to http://jhipster.github.io/docker_compose.html where everything is explained about how to mount your docker DB ?

**Comment by pascalgrimaud** [comment]
Thanks @cbornet for feedback. I'll try to do it this weekend :
* merge conflict
* remove mysql install
* try to understand why u need sudo for using docker-compose. did u need to "sudo docker ps" too ? Or simply "docker ps" ?

**Comment by cbornet** [comment]
@pascalgrimaud my fault : I forgot to login/logout (I didn't test from vagrant provisionning)

**Comment by cbornet** [comment]
Can we not remove jhipster-travis-build but keep it in a ```.jhipster-travis-build``` folder so that we can speed up new project generation by copying node_modules from it (and it's easy to have it up-to-date sing its under git) ?

**Comment by pascalgrimaud** [comment]
* keeping full jhipster-travis-build => near 1G
* just keepking .m2 => 320mo

I think the best tip is to generate a project 1st time (download full node_modules/) and copy this node_modules/ when generate a new project

**Comment by cbornet** [comment]
We could even have a script ```jhipster_project.sh```
```shell
#!/bin/bash
git -C /home/vagrant/.jhipster-travis-build pull --ff origin master
cp -R .jhipster-travis-build/node_modules ./
yo jhipster
```

**Comment by cbornet** [comment]
But it's true that copying 1G at each new project is a bit annoying...

**Comment by pascalgrimaud** [comment]
* merge conflict => done
* remove mysql install => done

So should we `docker pull mysql:5.7.9` ?

**Comment by cbornet** [comment]
Can you keep the installation of mysql-workbench ?

**Comment by jdubois** [comment]
I tried to run this, and I got:

    ==> default: /tmp/vagrant-shell: 86: /tmp/vagrant-shell: Syntax error: redirection unexpected
    Vagrant can't use the requested machine because it is locked! This
    means that another Vagrant process is currently reading or modifying
    the machine. Please wait for that Vagrant process to end and try
    again. Details about the machine are shown below:
    
    Name: default
    Provider: virtualbox

Anyway, I'm wondering if using Docker isn't too complicated in the end: I only wanted to have MySQL, as this is by far what most people are using, and this goes far beyond our initial need.

**Comment by pascalgrimaud** [comment]
I agree, maybe too complicated right now
If users want to use docker, they can read http://jhipster.github.io/docker_compose.html

**Comment by jdubois** [comment]
@pascalgrimaud yes, this might also be a better option in the end

**Comment by pascalgrimaud** [comment]
So, only keep the .m2/repository ?
```
# provide m2
mkdir -p /home/vagrant/.m2
git clone https://github.com/jhipster/jhipster-travis-build /home/vagrant/jhipster-travis-build
mv /home/vagrant/jhipster-travis-build/repository /home/vagrant/.m2/
rm -Rf /home/vagrant/jhipster-travis-build
```

And must install mysql-server back

**Comment by jdubois** [comment]
Yes for me, at least for the moment

**Comment by pascalgrimaud** [comment]
I can make a cleaner PR tonight : just provide .m2
So close this ?

**Comment by jdubois** [comment]
Yes!

**Comment by cbornet** [comment]
I think it's too bad to remove docker installation !! It's really useful for people that don't use MySQL !

**Pull request closed without merging**
