### PR TITLE
Fix Path for Yarn

### PR DESCRIPTION
**Pull request by pascalgrimaud**
It can be a little bit strange, the way I choose to install yarn, but I didn't find another one:
- if I don't use `su -c`, Yarn will install yo, bower, gulp, generator-jhipster under root user
- if I use vagrant user, it can't write on /usr/bin

Everything works fine for me:
```
➜  demo yarn --version
0.21.3
➜  demo yo --version
g1.8.5
➜  demo gulp --version
[01:55:10] CLI version 3.9.1
➜  demo yo jhipster
 
        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://jhipster.github.io

Welcome to the JHipster Generator v4.0.7
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /home/vagrant/projects/demo
```

Fix https://github.com/jhipster/jhipster-devbox/issues/76

### CODE REVIEW

**Comment by jdubois** [comment]
Great job - I know the issue, I spent the evening on it and didn't find a solution !!!!!

**Comment by pascalgrimaud** [comment]
Plz, don't merge yet!
I'm working on the Docker image to be consistent and I think I find a better way! :-)

**Comment by jdubois** [comment]
No problem, I also wanted to improve a couple of other things anyway....

Le 4 mars 2017 10:06 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
I got it. The solution is to use `yarn config set prefix /home/vagrant/.yarn-global` as suggested on Yarn tickets. I squash and update my PR.

Here my tests:
```
➜  ~ yarn --version
0.21.3
➜  ~ yo --version
1.8.5
➜  ~ bower --version
1.8.0
➜  ~ gulp --version
[09:40:22] CLI version 3.9.1
➜  ~ echo $PATH
/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/bin:/home/vagrant/.yarn-global/bin:/home/vagrant/.yarn/bin:/home/vagrant/.config/yarn/global/node_modules/.bin
➜  ~ yarn global bin
/home/vagrant/.yarn-global/bin
➜  ~ 
```

I created an Angular2 project and everything works fine for me.

**Comment by jdubois** [comment]
I tested this option yesterday and had tons of issues... At least now I
know it quite well, so I'll be able to test your config easily.

Le 4 mars 2017 10:49 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Pull request merged**
