### PR TITLE
Reduce box size and clean history

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Comment by jdubois** [comment]
@cbornet I need to rollback, I get:

    ==> default: dd:
    ==> default: error writing ‘/EMPTY’
    ==> default: : No space left on device
    ==> default: 34419+0 records in
    ==> default: 34418+0 records out
    ==> default: 36090126336 bytes (36 GB) copied
    ==> default: , 41.8366 s, 863 MB/s
    ==> default: /tmp/vagrant-shell: 131: /tmp/vagrant-shell: history: not found
    The SSH command responded with a non-zero exit status. Vagrant
    assumes that this means the command failed. The output for this command
    should be in the log above. Please read the output to determine what
went wrong.

**Comment by cbornet** [comment]
I think it comes from the ```history -c``` command that fails (don't know why...)
All the other should work even though it is ugly to have errors in the vagrant console.
I will have a look asap.

**Comment by cbornet** [comment]
TIL vagrant provisionning executes the script with sudo (by default) and the history command is not in sudo and fails. As it is the last command in the setup.sh the script exits with an error and vagrant complains.
So the good way to clean history would be
```
unset HISTFILE
[ -f /root/.bash_history ] && rm /root/.bash_history
[ -f /home/vagrant/.bash_history ] && rm /home/vagrant/.bash_history
```
as described [here](https://gist.github.com/justindowning/5670884). Anyway, vagrant provisions through an ssh script, it's maybe not appropriate to do this cleaning so we can just forget about it for now.

As for the disk zeroing, can we reactivate it as it really reduces the size of the box ?

Also, as the script is run as sudo, we can remove all the sudo in the script.

**Comment by cbornet** [comment]
Another source of inspiration for compacting the box:
https://github.com/chef/bento/blob/master/scripts/common/minimize.sh
https://github.com/chef/bento/blob/master/scripts/ubuntu/cleanup.sh

**Comment by cbornet** [comment]
After zeroing v0.2.1:
size before = 3.61 GB
size after = 2.32GB

**Comment by jdubois** [comment]
For the history: this isn't very important anyway
For reducing the size: yes that's a very good improvement, I'm testing this again right now

**Comment by jdubois** [comment]
No I still have a:

    No space left on device

**Comment by cbornet** [comment]
If you have it in the vagrant provisioning log this is "normal" : this is how the dd command ends. Then the rm command should free the space again. When you start the box, does the gui spawns correctly ? Is the /EMPTY file correctly deleted ?
If you feel that the dd error message in the vagrant log should not be printed this can be removed by redirecting the stderr
```
dd if=/dev/zero of=/EMPTY bs=1M > /dev/null 2>&1
rm -f /EMPTY
```

**Pull request merged**
